v1.0.10
missing v1.0.1 on pypi (my misstake) :
  HTTPError: 400 Client Error: This filename has already been used, use a different version. See https://pypi.org/help/#file-name-reuse for url: https://upload.pypi.org/legacy/

  ci skip